<?php

use Illuminate\Database\Seeder;

class AssetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	/*stock_market*/
        DB::table('assets')->insert([
            'symbol'         => 'NFLX',
            'name'         => 'Netflix Inc.',
            'type'      => 'stock_market',
            'status'  => 'off',
            'created_at' => now()
        ]);

        /*physical*/
        $physicals = [	
        	
        	['symbol' =>'AED', 'name' => 'United Arab Emirates Dirham', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AFN', 'name' => 'Afghan Afghani', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ALL', 'name' => 'Albanian Lek', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AMD', 'name' => 'Armenian Dram', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ANG', 'name' => 'Netherlands Antillean Guilder', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AOA', 'name' => 'Angolan Kwanza', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ARS', 'name' => 'Argentine Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AUD', 'name' => 'Australian Dollar', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'AWG', 'name' => 'Aruban Florin', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AZN', 'name' => 'Azerbaijani Manat', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BAM', 'name' => 'Bosnia-Herzegovina Convertible Mark', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BBD', 'name' => 'Barbadian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BDT', 'name' => 'Bangladeshi Taka', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BGN', 'name' => 'Bulgarian Lev', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BHD', 'name' => 'Bahraini Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BIF', 'name' => 'Burundian Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BMD', 'name' => 'Bermudan Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BND', 'name' => 'Brunei Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BOB', 'name' => 'Bolivian Boliviano', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BRL', 'name' => 'Brazilian Real', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BSD', 'name' => 'Bahamian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BTN', 'name' => 'Bhutanese Ngultrum', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BWP', 'name' => 'Botswanan Pula', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BZD', 'name' => 'Belize Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CAD', 'name' => 'Canadian Dollar', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'CDF', 'name' => 'Congolese Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CHF', 'name' => 'Swiss Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CLF', 'name' => 'Chilean Unit of Account UF', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CLP', 'name' => 'Chilean Peso', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'CNH', 'name' => 'Chinese Yuan Offshore', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CNY', 'name' => 'Chinese Yuan', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'COP', 'name' => 'Colombian Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CUP', 'name' => 'Cuban Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CVE', 'name' => 'Cape Verdean Escudo', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CZK', 'name' => 'Czech Republic Koruna', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DJF', 'name' => 'Djiboutian Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DKK', 'name' => 'Danish Krone', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DOP', 'name' => 'Dominican Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DZD', 'name' => 'Algerian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'EGP', 'name' => 'Egyptian Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ERN', 'name' => 'Eritrean Nakfa', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ETB', 'name' => 'Ethiopian Birr', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'EUR', 'name' => 'Euro', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'FJD', 'name' => 'Fijian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'FKP', 'name' => 'Falkland Islands Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GBP', 'name' => 'British Pound Sterling', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'GEL', 'name' => 'Georgian Lari', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GHS', 'name' => 'Ghanaian Cedi', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GIP', 'name' => 'Gibraltar Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GMD', 'name' => 'Gambian Dalasi', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GNF', 'name' => 'Guinean Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GTQ', 'name' => 'Guatemalan Quetzal', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GYD', 'name' => 'Guyanaese Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HKD', 'name' => 'Hong Kong Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HNL', 'name' => 'Honduran Lempira', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HRK', 'name' => 'Croatian Kuna', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HTG', 'name' => 'Haitian Gourde', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HUF', 'name' => 'Hungarian Forint', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'IDR', 'name' => 'Indonesian Rupiah', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ILS', 'name' => 'Israeli New Sheqel', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'INR', 'name' => 'Indian Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'IQD', 'name' => 'Iraqi Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'IRR', 'name' => 'Iranian Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ISK', 'name' => 'Icelandic Krona', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JEP', 'name' => 'Jersey Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JMD', 'name' => 'Jamaican Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JOD', 'name' => 'Jordanian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JPY', 'name' => 'Japanese Yen', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'KES', 'name' => 'Kenyan Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KGS', 'name' => 'Kyrgystani Som', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KHR', 'name' => 'Cambodian Riel', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KMF', 'name' => 'Comorian Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KPW', 'name' => 'North Korean Won', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KRW', 'name' => 'South Korean Won', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KWD', 'name' => 'Kuwaiti Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KYD', 'name' => 'Cayman Islands Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KZT', 'name' => 'Kazakhstani Tenge', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LAK', 'name' => 'Laotian Kip', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LBP', 'name' => 'Lebanese Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LKR', 'name' => 'Sri Lankan Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LRD', 'name' => 'Liberian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LSL', 'name' => 'Lesotho Loti', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LYD', 'name' => 'Libyan Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MAD', 'name' => 'Moroccan Dirham', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MDL', 'name' => 'Moldovan Leu', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MGA', 'name' => 'Malagasy Ariary', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MKD', 'name' => 'Macedonian Denar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MMK', 'name' => 'Myanma Kyat', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MNT', 'name' => 'Mongolian Tugrik', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MOP', 'name' => 'Macanese Pataca', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MRO', 'name' => 'Mauritanian Ouguiya (pre-2018)', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MRU', 'name' => 'Mauritanian Ouguiya', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MUR', 'name' => 'Mauritian Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MVR', 'name' => 'Maldivian Rufiyaa', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MWK', 'name' => 'Malawian Kwacha', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MXN', 'name' => 'Mexican Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MYR', 'name' => 'Malaysian Ringgit', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MZN', 'name' => 'Mozambican Metical', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NAD', 'name' => 'Namibian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NGN', 'name' => 'Nigerian Naira', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NOK', 'name' => 'Norwegian Krone', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NPR', 'name' => 'Nepalese Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NZD', 'name' => 'New Zealand Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'OMR', 'name' => 'Omani Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PAB', 'name' => 'Panamanian Balboa', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PEN', 'name' => 'Peruvian Nuevo Sol', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PGK', 'name' => 'Papua New Guinean Kina', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PHP', 'name' => 'Philippine Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PKR', 'name' => 'Pakistani Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PLN', 'name' => 'Polish Zloty', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PYG', 'name' => 'Paraguayan Guarani', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'QAR', 'name' => 'Qatari Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RON', 'name' => 'Romanian Leu', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RSD', 'name' => 'Serbian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RUB', 'name' => 'Russian Ruble', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RUR', 'name' => 'Old Russian Ruble', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RWF', 'name' => 'Rwandan Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SAR', 'name' => 'Saudi Riyal', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SBDf', 'name' => 'Solomon Islands Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SCR', 'name' => 'Seychellois Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SDG', 'name' => 'Sudanese Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SEK', 'name' => 'Swedish Krona', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SGD', 'name' => 'Singapore Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SHP', 'name' => 'Saint Helena Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SLL', 'name' => 'Sierra Leonean Leone', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SOS', 'name' => 'Somali Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SRD', 'name' => 'Surinamese Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SYP', 'name' => 'Syrian Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SZL', 'name' => 'Swazi Lilangeni', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'THB', 'name' => 'Thai Baht', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TJS', 'name' => 'Tajikistani Somoni', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TMT', 'name' => 'Turkmenistani Manat', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TND', 'name' => 'Tunisian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TOP', 'name' => "Tongan Pa'anga", 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TRY', 'name' => 'Turkish Lira', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TTD', 'name' => 'Trinidad and Tobago Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TWD', 'name' => 'New Taiwan Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TZS', 'name' => 'Tanzanian Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'UAH', 'name' => 'Ukrainian Hryvnia', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'UGX', 'name' => 'Ugandan Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'USD', 'name' => 'United States Dollar', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'UYU', 'name' => 'Uruguayan Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'UZS', 'name' => 'Uzbekistan Som', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'VND', 'name' => 'Vietnamese Dong', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'VUV', 'name' => 'Vanuatu Vatu', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'WST', 'name' => 'Samoan Tala', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XAF', 'name' => 'CFA Franc BEAC', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XAG', 'name' => 'Silver Ounce', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XAU', 'name' => 'Gold Ounce', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XCD', 'name' => 'East Caribbean Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XDR', 'name' => 'Special Drawing Rights', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XOF', 'name' => 'CFA Franc BCEAO', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XPF', 'name' => 'CFP Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'YER', 'name' => 'Yemeni Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ZAR', 'name' => 'South African Rand', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ZMW', 'name' => 'Zambian Kwacha', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ZWL', 'name' => 'Zimbabwean Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        ];

        foreach ($physicals as $physical
        ) {
        	DB::table('assets')->insert($physical);
        }
    }
}
