<?php

use Illuminate\Database\Seeder;

class AssetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	/*stock_market*/

        $stock_markets = [
            ['symbol' =>'NFLX', 'name' => 'Netflix Inc.', 'type' => 'stock_market', 'status' => 'on', 'created_at' => now()]
        ];

        foreach ($stock_markets as $stock
        ) {
            DB::table('assets')->insert($stock);
        }

        /*physical*/
        $physicals = [	
        	
        	['symbol' =>'AED', 'name' => 'United Arab Emirates Dirham', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AFN', 'name' => 'Afghan Afghani', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ALL', 'name' => 'Albanian Lek', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AMD', 'name' => 'Armenian Dram', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ANG', 'name' => 'Netherlands Antillean Guilder', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AOA', 'name' => 'Angolan Kwanza', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ARS', 'name' => 'Argentine Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AUD', 'name' => 'Australian Dollar', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'AWG', 'name' => 'Aruban Florin', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'AZN', 'name' => 'Azerbaijani Manat', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BAM', 'name' => 'Bosnia-Herzegovina Convertible Mark', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BBD', 'name' => 'Barbadian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BDT', 'name' => 'Bangladeshi Taka', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BGN', 'name' => 'Bulgarian Lev', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BHD', 'name' => 'Bahraini Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BIF', 'name' => 'Burundian Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BMD', 'name' => 'Bermudan Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BND', 'name' => 'Brunei Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BOB', 'name' => 'Bolivian Boliviano', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BRL', 'name' => 'Brazilian Real', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BSD', 'name' => 'Bahamian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BTN', 'name' => 'Bhutanese Ngultrum', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BWP', 'name' => 'Botswanan Pula', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'BZD', 'name' => 'Belize Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CAD', 'name' => 'Canadian Dollar', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'CDF', 'name' => 'Congolese Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CHF', 'name' => 'Swiss Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CLF', 'name' => 'Chilean Unit of Account UF', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CLP', 'name' => 'Chilean Peso', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'CNH', 'name' => 'Chinese Yuan Offshore', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CNY', 'name' => 'Chinese Yuan', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'COP', 'name' => 'Colombian Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CUP', 'name' => 'Cuban Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CVE', 'name' => 'Cape Verdean Escudo', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'CZK', 'name' => 'Czech Republic Koruna', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DJF', 'name' => 'Djiboutian Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DKK', 'name' => 'Danish Krone', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DOP', 'name' => 'Dominican Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'DZD', 'name' => 'Algerian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'EGP', 'name' => 'Egyptian Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ERN', 'name' => 'Eritrean Nakfa', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ETB', 'name' => 'Ethiopian Birr', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'EUR', 'name' => 'Euro', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'FJD', 'name' => 'Fijian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'FKP', 'name' => 'Falkland Islands Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GBP', 'name' => 'British Pound Sterling', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'GEL', 'name' => 'Georgian Lari', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GHS', 'name' => 'Ghanaian Cedi', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GIP', 'name' => 'Gibraltar Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GMD', 'name' => 'Gambian Dalasi', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GNF', 'name' => 'Guinean Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GTQ', 'name' => 'Guatemalan Quetzal', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'GYD', 'name' => 'Guyanaese Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HKD', 'name' => 'Hong Kong Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HNL', 'name' => 'Honduran Lempira', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HRK', 'name' => 'Croatian Kuna', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HTG', 'name' => 'Haitian Gourde', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'HUF', 'name' => 'Hungarian Forint', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'IDR', 'name' => 'Indonesian Rupiah', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ILS', 'name' => 'Israeli New Sheqel', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'INR', 'name' => 'Indian Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'IQD', 'name' => 'Iraqi Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'IRR', 'name' => 'Iranian Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ISK', 'name' => 'Icelandic Krona', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JEP', 'name' => 'Jersey Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JMD', 'name' => 'Jamaican Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JOD', 'name' => 'Jordanian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'JPY', 'name' => 'Japanese Yen', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'KES', 'name' => 'Kenyan Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KGS', 'name' => 'Kyrgystani Som', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KHR', 'name' => 'Cambodian Riel', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KMF', 'name' => 'Comorian Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KPW', 'name' => 'North Korean Won', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KRW', 'name' => 'South Korean Won', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KWD', 'name' => 'Kuwaiti Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KYD', 'name' => 'Cayman Islands Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'KZT', 'name' => 'Kazakhstani Tenge', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LAK', 'name' => 'Laotian Kip', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LBP', 'name' => 'Lebanese Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LKR', 'name' => 'Sri Lankan Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LRD', 'name' => 'Liberian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LSL', 'name' => 'Lesotho Loti', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'LYD', 'name' => 'Libyan Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MAD', 'name' => 'Moroccan Dirham', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MDL', 'name' => 'Moldovan Leu', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MGA', 'name' => 'Malagasy Ariary', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MKD', 'name' => 'Macedonian Denar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MMK', 'name' => 'Myanma Kyat', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MNT', 'name' => 'Mongolian Tugrik', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MOP', 'name' => 'Macanese Pataca', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MRO', 'name' => 'Mauritanian Ouguiya (pre-2018)', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MRU', 'name' => 'Mauritanian Ouguiya', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MUR', 'name' => 'Mauritian Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MVR', 'name' => 'Maldivian Rufiyaa', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MWK', 'name' => 'Malawian Kwacha', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MXN', 'name' => 'Mexican Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MYR', 'name' => 'Malaysian Ringgit', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'MZN', 'name' => 'Mozambican Metical', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NAD', 'name' => 'Namibian Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NGN', 'name' => 'Nigerian Naira', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NOK', 'name' => 'Norwegian Krone', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NPR', 'name' => 'Nepalese Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'NZD', 'name' => 'New Zealand Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'OMR', 'name' => 'Omani Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PAB', 'name' => 'Panamanian Balboa', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PEN', 'name' => 'Peruvian Nuevo Sol', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PGK', 'name' => 'Papua New Guinean Kina', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PHP', 'name' => 'Philippine Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PKR', 'name' => 'Pakistani Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PLN', 'name' => 'Polish Zloty', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'PYG', 'name' => 'Paraguayan Guarani', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'QAR', 'name' => 'Qatari Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RON', 'name' => 'Romanian Leu', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RSD', 'name' => 'Serbian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RUB', 'name' => 'Russian Ruble', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RUR', 'name' => 'Old Russian Ruble', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'RWF', 'name' => 'Rwandan Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SAR', 'name' => 'Saudi Riyal', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SBDf', 'name' => 'Solomon Islands Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SCR', 'name' => 'Seychellois Rupee', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SDG', 'name' => 'Sudanese Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SEK', 'name' => 'Swedish Krona', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SGD', 'name' => 'Singapore Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SHP', 'name' => 'Saint Helena Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SLL', 'name' => 'Sierra Leonean Leone', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SOS', 'name' => 'Somali Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SRD', 'name' => 'Surinamese Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SYP', 'name' => 'Syrian Pound', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'SZL', 'name' => 'Swazi Lilangeni', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'THB', 'name' => 'Thai Baht', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TJS', 'name' => 'Tajikistani Somoni', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TMT', 'name' => 'Turkmenistani Manat', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TND', 'name' => 'Tunisian Dinar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TOP', 'name' => "Tongan Pa'anga", 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TRY', 'name' => 'Turkish Lira', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TTD', 'name' => 'Trinidad and Tobago Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TWD', 'name' => 'New Taiwan Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'TZS', 'name' => 'Tanzanian Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'UAH', 'name' => 'Ukrainian Hryvnia', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'UGX', 'name' => 'Ugandan Shilling', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'USD', 'name' => 'United States Dollar', 'type' => 'physical', 'status' => 'on', 'created_at' => now()],
        	['symbol' =>'UYU', 'name' => 'Uruguayan Peso', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'UZS', 'name' => 'Uzbekistan Som', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'VND', 'name' => 'Vietnamese Dong', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'VUV', 'name' => 'Vanuatu Vatu', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'WST', 'name' => 'Samoan Tala', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XAF', 'name' => 'CFA Franc BEAC', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XAG', 'name' => 'Silver Ounce', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XAU', 'name' => 'Gold Ounce', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XCD', 'name' => 'East Caribbean Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XDR', 'name' => 'Special Drawing Rights', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XOF', 'name' => 'CFA Franc BCEAO', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'XPF', 'name' => 'CFP Franc', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'YER', 'name' => 'Yemeni Rial', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ZAR', 'name' => 'South African Rand', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ZMW', 'name' => 'Zambian Kwacha', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        	['symbol' =>'ZWL', 'name' => 'Zimbabwean Dollar', 'type' => 'physical', 'status' => 'off', 'created_at' => now()],
        ];

        foreach ($physicals as $physical) {
        	DB::table('assets')->insert($physical);
        }

        $cryptos = [
            ['symbol' =>'1ST', 'name' => 'FirstBlood.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'2GIVE', 'name' => 'GiveCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'808', 'name' => '808Coin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ABT', 'name' => 'ArcBlock', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ABY', 'name' => 'ArtByte', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AC', 'name' => 'AsiaCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ACT', 'name' => 'Achain', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ADA', 'name' => 'Cardano', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ADT', 'name' => 'adToken', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ADX', 'name' => 'AdEx', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AE', 'name' => 'Aeternity', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AEON', 'name' => 'Aeon', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AGI', 'name' => 'SingularityNET', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AGRS', 'name' => 'IDNI-Agoras', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AI', 'name' => 'POLY-AI', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AID', 'name' => 'AidCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AION', 'name' => 'Aion', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AIR', 'name' => 'AirToken', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AKY', 'name' => 'Akuya-Coin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ALIS', 'name' => 'ALIS', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AMBER', 'name' => 'AmberCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AMP', 'name' => 'Synereo', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ANC', 'name' => 'Anoncoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ANT', 'name' => 'Aragon', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'APPC', 'name' => 'AppCoins', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'APX', 'name' => 'APX-Ventures', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ARDR', 'name' => 'Ardor', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ARK', 'name' => 'Ark', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ARN', 'name' => 'Aeron', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AST', 'name' => 'AirSwap', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ATB', 'name' => 'ATBCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ATM', 'name' => 'ATMChain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ATS', 'name' => 'Authorship.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AUR', 'name' => 'Auroracoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'AVT', 'name' => 'Aventus.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'B3', 'name' => 'B3Coin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BAT', 'name' => 'Basic-Attention-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BAY', 'name' => 'BitBay.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BBR', 'name' => 'Boolberry.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCAP', 'name' => 'BCAP', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCC', 'name' => 'BitConnect', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCD', 'name' => 'Bitcoin-Diamond.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCH', 'name' => 'Bitcoin-Cash.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCN', 'name' => 'Bytecoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCPT', 'name' => 'BlockMason-Credit-Protocol-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCX', 'name' => 'BitcoinX.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BCY', 'name' => 'BitCrystals.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BDL', 'name' => 'Bitdeal.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BEE', 'name' => 'Bee-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BELA', 'name' => 'BelaCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BET', 'name' => 'DAO-Casino.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BFT', 'name' => 'BF-Token', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BIS', 'name' => 'Bismuth', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BITB', 'name' => 'BitBean', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BITBTC', 'name' => 'BitBTC', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BITCNY', 'name' => 'BitCNY', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BITEUR', 'name' => 'BitEUR', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BITGOLD', 'name' => 'BitGOLD', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BITSILVER', 'name' => 'BitSILVER', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BITUSD', 'name' => 'BitUSD', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BIX', 'name' => 'Bibox-Token', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BLITZ', 'name' => 'Blitzcash', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BLK', 'name' => 'Blackcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BLN', 'name' => 'Bolenum', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BLOCK', 'name' => 'Blocknet', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BLZ', 'name' => 'Bluzelle', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BMC', 'name' => 'Blackmoon-Crypto', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BNB', 'name' => 'Binance-Coin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BNT', 'name' => 'Bancor-Network-Toke', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BNTY', 'name' => 'Bounty0x', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BOST', 'name' => 'BoostCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BOT', 'name' => 'Bodhi', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BQ', 'name' => 'bitqy', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BRD', 'name' => 'Bread', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BRK', 'name' => 'Breakout-Coin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BRX', 'name' => 'Breakout-Stake', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTA', 'name' => 'Bata', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTC', 'name' => 'Bitcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTCD', 'name' => 'BitcoinDark', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTCP', 'name' => 'Bitcoin-Private', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTG', 'name' => 'Bitcoin-Gold', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],    
            ['symbol' =>'BTM', 'name' => 'Bitmark', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTS', 'name' => 'BitShares', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTSR', 'name' => 'BTSR', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BTX', 'name' => 'Bitcore', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BURST', 'name' => 'Burstcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BUZZ', 'name' => 'BuzzCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BYC', 'name' => 'Bytecent', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'BYTOM', 'name' => 'Bytom', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'C20', 'name' => 'Crypto20', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CANN', 'name' => 'CannabisCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CAT', 'name' => 'BlockCAT', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CCRB', 'name' => 'CryptoCarbon', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CDT', 'name' => 'Blox', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CFI', 'name' => 'Cofound-it', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CHAT', 'name' => 'ChatCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CHIPS', 'name' => 'Chips', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CLAM', 'name' => 'Clams', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CLOAK', 'name' => 'CloakCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CMP', 'name' => 'Compcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CMT', 'name' => 'CyberMiles', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CND', 'name' => 'Cindicator', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CNX', 'name' => 'Cryptonex', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'COFI', 'name' => 'CoinFi', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'COSS', 'name' => 'COSS', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'COVAL', 'name' => 'Circuits-Of-Valu', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CRBIT', 'name' => 'CreditBIT', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'CREA', 'name' => 'CreativeCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CREDO', 'name' => 'Credo', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CRW', 'name' => 'Crown', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CSNO', 'name' => 'BitDice', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CTR', 'name' => 'Centra', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CTXC', 'name' => 'Cortex', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'CURE', 'name' => 'CureCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'CVC', 'name' => 'Civic', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DAI', 'name' => 'Dai', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DAR', 'name' => 'Darcrus', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DASH', 'name' => 'Dash', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DATA', 'name' => 'DATAcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'DAY', 'name' => 'Dhronologic', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DBC', 'name' => 'DeepBrain-Chai', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DBIX', 'name' => 'DubaiCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DCN', 'name' => 'Dentacoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DCR', 'name' => 'ecred', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DCT', 'name' => 'DECENT', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'DDF', 'name' => 'Digital-Developers-Fund', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DENT', 'name' => 'Dent', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DFS', 'name' => 'DFSCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DGB', 'name' => 'DigiByte', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DGC', 'name' => 'Digitalcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DGD', 'name' => 'DigixDAO', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'DICE', 'name' => 'Etheroll', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DLT', 'name' => 'Agrello-Delta', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DMD', 'name' => 'Diamond', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DMT', 'name' => 'DMarket', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DNT', 'name' => 'district0x', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DOGE', 'name' => 'DogeCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'DOPE', 'name' => 'DopeCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DRGN', 'name' => 'Dragonchain', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DTA', 'name' => 'Data', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DTB', 'name' => 'Databits', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'DYN', 'name' => 'Dynamic', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EAC', 'name' => 'EarthCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'EBST', 'name' => 'eBoost', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EBTC', 'name' => 'eBTC', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ECC', 'name' => 'ECC', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ECN', 'name' => 'E-coin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EDG', 'name' => 'Edgeless', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EDO', 'name' => 'Eidoo', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'EFL', 'name' => 'Electronic-Gulden', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EGC', 'name' => 'EverGreenCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EKT', 'name' => 'EDUCare', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ELA', 'name' => 'Elastos', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ELEC', 'name' => 'Electrify.Asia', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ELF', 'name' => 'aelf', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'ELIX', 'name' => 'Elixir', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EMB', 'name' => 'Embercoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EMC', 'name' => 'Emercoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EMC2', 'name' => 'Einsteinium', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ENG', 'name' => 'Enigma', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ENJ', 'name' => 'Enjin-Coin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],     
             ['symbol' =>'ENRG', 'name' => 'EnergyCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EOS', 'name' => 'EOS', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EOT', 'name' => 'EOT-Token', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EQT', 'name' => 'EquiTrader', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ERC', 'name' => 'EuropeCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ETC', 'name' => 'Ethereum-Classic', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'ETH', 'name' => 'Ethereum', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ETHD', 'name' => 'Ethereum-Dark', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ETHOS', 'name' => 'Ethos', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ETN', 'name' => 'Electroneum', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ETP', 'name' => 'Metaverse-Entropy', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ETT', 'name' => 'EncryptoTel', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'EVE', 'name' => 'Devery', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EVX', 'name' => 'Everex', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EXCL', 'name' => 'ExclusiveCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'EXP', 'name' => 'Expanse', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'FCT', 'name' => 'Factom', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'FLDC', 'name' => 'FoldingCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'FLO', 'name' => 'FlorinCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'FLT', 'name' => 'FlutterCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'FRST', 'name' => 'FirstCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'FTC', 'name' => 'Feathercoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'FUEL', 'name' => 'Etherparty', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'FUN', 'name' => 'FunFair', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'GAM', 'name' => 'Gambit', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GAME', 'name' => 'GameCredits', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GAS', 'name' => 'Gas', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GBG', 'name' => 'Golos Gold', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GBX', 'name' => 'GoByte', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GBYTE', 'name' => 'Byteball', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'GCR', 'name' => 'GCRCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GEO', 'name' => 'GeoCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GLD', 'name' => 'GoldCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GNO', 'name' => 'Gnosis-Token', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GNT', 'name' => 'Golem-Tokens', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GOLOS', 'name' => 'Golos', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'GRC', 'name' => 'Gridcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GRS', 'name' => 'Groestlcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GRWI', 'name' => 'Growers-International', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GTC', 'name' => 'Game', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GTO', 'name' => 'Gifto', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GUP', 'name' => 'Guppy', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'GVT', 'name' => 'Genesis-Vision', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'GXS', 'name' => 'GXShares', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'HBN', 'name' => 'HoboNickels', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'HEAT', 'name' => 'HEAT', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'HMQ', 'name' => 'Humaniq', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'HPB', 'name' => 'High-Performance-Blockchain', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'HSR', 'name' => 'Hshare', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'HUSH', 'name' => 'Hush', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'HVN', 'name' => 'Hive', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'HXX', 'name' => 'HexxCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ICN', 'name' => 'ICONOMI', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ICX', 'name' => 'ICON', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
             ['symbol' =>'IFC', 'name' => 'Infinitecoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IFT', 'name' => 'investFeed', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IGNIS', 'name' => 'Ignis', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'INCNT', 'name' => 'Incent', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IND', 'name' => 'Indorse-Token', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'INF', 'name' => 'InfChain', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],   
            ['symbol' =>'INK', 'name' => 'Ink', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'INS', 'name' => 'INS-Ecosystem', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'INSTAR', 'name' => 'Insights-Network', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'INT', 'name' => 'Internet-Node-Token', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'INXT', 'name' => 'Internxt', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IOC', 'name' => 'IOCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ION', 'name' => 'ION', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IOP', 'name' => 'Internet-of-People', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IOST', 'name' => 'IOStoken', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IOTA', 'name' => 'IOTA', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IOTX', 'name' => 'IoTeX', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IQT', 'name' => 'Iquant-Chain', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ITC', 'name' => 'IoT-Chain', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IXC', 'name' => 'iXcoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'IXT', 'name' => 'InsureX', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'J8T', 'name' => 'JET8', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'JNT', 'name' => 'Jibrel-Network', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'KCS', 'name' => 'KuCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'KICK', 'name' => 'KickCoin', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'KIN', 'name' => 'KIN', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'KMD', 'name' => 'Komodo.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'KNC', 'name' => 'Kyber-Network.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'KORE', 'name' => 'KoreCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LBC', 'name' => 'LBRY-Credits.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LCC', 'name' => 'Litecoin-Cash.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LEND', 'name' => 'EthLend.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LEV', 'name' => 'Leverj.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LGD', 'name' => 'Legends-Room.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LINDA', 'name' => 'Linda.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LINK', 'name' => 'ChainLink.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LKK', 'name' => 'Lykke.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LMC', 'name' => 'LoMoCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LOCI', 'name' => 'LOCIcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LOOM', 'name' => 'Loom-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LRC', 'name' => 'Loopring.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LSK', 'name' => 'Lisk.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LTC', 'name' => 'Litecoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'LUN', 'name' => 'Lunyr.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MAID', 'name' => 'MaidSafeCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MANA', 'name' => 'Decentraland.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MAX', 'name' => 'Maxcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MBRS', 'name' => 'Embers.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MCAP', 'name' => 'MCAP.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MCO', 'name' => 'Monaco.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MDA', 'name' => 'Moeda-Loyalty-Points.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MEC', 'name' => 'Megacoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MED', 'name' => 'MediBlock.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MEME', 'name' => 'Memetic.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MER', 'name' => 'Mercury.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MGC', 'name' => 'MergeCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MGO', 'name' => 'MobileGo.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MINEX', 'name' => 'Minex.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MINT', 'name' => 'Mintcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MITH', 'name' => 'Mithril.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MKR', 'name' => 'Maker.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MLN', 'name' => 'Melon.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MNE', 'name' => 'Minereum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MNX', 'name' => 'MinexCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MOD', 'name' => 'Modum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MONA', 'name' => 'MonaCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MRT', 'name' => 'Miners-Reward-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MSP', 'name' => 'Mothership.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MTH', 'name' => 'Monetha.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MTN', 'name' => 'MedToken.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MUE', 'name' => 'MonetaryUnit.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MUSIC', 'name' => 'Musicoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MYB', 'name' => 'yBit-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MYST', 'name' => 'Mysterium.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'MZC', 'name' => 'Mazacoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NAMO', 'name' => 'Namocoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NANO', 'name' => 'Nano.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NAS', 'name' => 'Nebulas-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NAV', 'name' => 'Nav-Coin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NBT', 'name' => 'NuBits.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NCASH', 'name' => 'Nucleus-Vision.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NDC', 'name' => 'NeverDie-Coin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NEBL', 'name' => 'Neblio.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NEO', 'name' => 'NEO.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NEOS', 'name' => 'NeosCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NET', 'name' => 'Nimiq.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NLC2', 'name' => 'NoLimitCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NLG', 'name' => 'Gulden.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NMC', 'name' => 'Namecoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NMR', 'name' => 'Numeraire.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NOBL', 'name' => 'NobleCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NOTE', 'name' => 'DNotes.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NPXS', 'name' => 'Pundi-X-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NSR', 'name' => 'NuShares.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NTO', 'name' => 'Fujinto.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NULS', 'name' => 'Nuls.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NVC', 'name' => 'Novacoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NXC', 'name' => 'Nexium.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NXS', 'name' => 'Nexus.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'NXT', 'name' => 'Nxt.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OAX', 'name' => 'openANX.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OBITS', 'name' => 'Obits.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OCL', 'name' => 'Oceanlab.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OCN', 'name' => 'Odyssey.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ODEM', 'name' => 'ODEM.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ODN', 'name' => 'Obsidian.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OF', 'name' => 'OFCOIN.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OK', 'name' => 'OKCash.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OMG', 'name' => 'OmiseGo.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OMNI', 'name' => 'Omni.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ONION', 'name' => 'DeepOnion.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ONT', 'name' => 'Ontology.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OPT', 'name' => 'Opus.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'OST', 'name' => 'Simple-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PART', 'name' => 'Particl.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PASC', 'name' => 'PascalCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PAY', 'name' => 'TenX.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PBL', 'name' => 'Pebbles.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PBT', 'name' => 'Primalbase-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PFR', 'name' => 'Payfair.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PING', 'name' => 'CryptoPing.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PINK', 'name' => 'Pinkcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PIVX', 'name' => 'PIVX.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PIX', 'name' => 'Lampix.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PLBT', 'name' => 'Polybius.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PLR', 'name' => 'Pillar.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PLU', 'name' => 'Pluton.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'POA', 'name' => 'POA-Networ.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'POE', 'name' => 'Poet.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'POLY', 'name' => 'Polymath.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'POSW', 'name' => 'PoSW-Coin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'POT', 'name' => 'PotCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'POWR', 'name' => 'Power-Ledger.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PPC', 'name' => 'Peercoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PPT', 'name' => 'Populous.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PPY', 'name' => 'Peerplays.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PRG', 'name' => 'Paragon-Coin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PRL', 'name' => 'Oyster-Pearl.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PRO', 'name' => 'Propy.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PST', 'name' => 'Primas.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PTC', 'name' => 'Pesetacoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PTOY', 'name' => 'Patientory.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'PURA', 'name' => 'Pura.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QASH', 'name' => 'QASH.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QAU', 'name' => 'Quantum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QLC', 'name' => 'Qlink.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QRK', 'name' => 'Quark.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QRL', 'name' => 'Quantum-Resistant-Ledger.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QSP', 'name' => 'Quantstamp', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QTL', 'name' => 'Quatloo.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QTUM', 'name' => 'Qtum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'QWARK', 'name' => 'Qwark.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'R', 'name' => 'Revain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RADS', 'name' => 'Radium.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RAIN', 'name' => 'Condensate.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RBIES', 'name' => 'Rubies.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RBX', 'name' => 'Ripto-Bux.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RBY', 'name' => 'RubyCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RCN', 'name' => 'Ripio-Credit-Network.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RDD', 'name' => 'ReddCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RDN', 'name' => 'Raiden-Network-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'REC', 'name' => 'Regalcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RED', 'name' => 'Redcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'REP', 'name' => 'Augur.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'REQ', 'name' => 'Request-Network.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RHOC', 'name' => 'RChain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RIC', 'name' => 'Riecoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RISE', 'name' => 'Rise.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RLC', 'name' => 'RLC-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RLT', 'name' => 'RouletteToken.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RPX', 'name' => 'Red-Pulse.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RRT', 'name' => 'Recovery-Right-Tokens.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RUFF', 'name' => 'Ruff.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RUP', 'name' => 'Rupee.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'RVT', 'name' => 'Rivetz.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SAFEX', 'name' => 'SafeExchangeCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SALT', 'name' => 'Santiment-Network-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SAN', 'name' => 'Salt.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SBD', 'name' => 'Steem-Dollars.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SBTC', 'name' => 'Super-Bitcoi.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SC', 'name' => 'Siacoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SEELE', 'name' => 'Seele.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SEQ', 'name' => 'Sequence.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SHIFT', 'name' => 'SHIFT.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SIB', 'name' => 'SIBCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SIGMA', 'name' => 'SIGMAcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SIGT', 'name' => 'Signatum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SJCX', 'name' => 'Storjcoin-X.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SKIN', 'name' => 'SkinCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SKY', 'name' => 'Skycoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SLR', 'name' => 'SolarCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SLS', 'name' => 'SaluS.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SMART', 'name' => 'SmartCash.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SMT', 'name' => 'SmartMesh.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SNC', 'name' => 'SunContract.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SNGLS', 'name' => 'SingularDTV.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SNM', 'name' => 'SONM.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SNRG', 'name' => 'Synergy.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SNT', 'name' => 'tatus-Network-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SOC', 'name' => 'All-Sports.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SOUL', 'name' => 'Phantasma.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SPANK', 'name' => 'SpankChain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SPC', 'name' => 'SpaceChain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SPHR', 'name' => 'Sphere.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SPR', 'name' => 'SpreadCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SRN', 'name' => 'Sirin-Labs-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'START', 'name' => 'Startcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'STEEM', 'name' => 'Steem.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'STK', 'name' => 'STK-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'STORJ', 'name' => 'Storj.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'STORM', 'name' => 'Storm.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'STQ', 'name' => 'Storiqa.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'STRAT', 'name' => 'Stratis.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'STX', 'name' => 'Stox.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SUB', 'name' => 'Substratum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SWFTC', 'name' => 'SwftCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SWIFT', 'name' => 'Bitswift.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SWT', 'name' => 'Swarm-City.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SYNX', 'name' => 'Syndicate.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'SYS', 'name' => 'SysCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TAAS', 'name' => 'Taas.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TAU', 'name' => 'Lamden.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TCC', 'name' => 'The-ChampCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TFL', 'name' => 'True-Flip.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'THC', 'name' => 'HempCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'THETA', 'name' => 'Theta-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TIME', 'name' => 'Time.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TIX', 'name' => 'Blocktix.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TKN', 'name' => 'TokenCard.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TKR', 'name' => 'Trackr.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TKS', 'name' => 'Tokes.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TNB', 'name' => 'Time-New-Bank.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TNT', 'name' => 'Tierion.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TOA', 'name' => 'ToaCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRAC', 'name' => 'OriginTrail.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRC', 'name' => 'Terracoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRCT', 'name' => 'Tracto.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRIG', 'name' => 'Triggers.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRST', 'name' => 'Trustcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRUE', 'name' => 'TrueChain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRUST', 'name' => 'TrustPlus.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TRX', 'name' => 'Tronix.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TUSD', 'name' => 'TrueUSD.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'TX', 'name' => 'TransferCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UBQ', 'name' => 'Ubiq.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UKG', 'name' => 'UnikoinGold.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ULA', 'name' => 'Ulatech.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UNB', 'name' => 'UnbreakableCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UNITY', 'name' => 'SuperNET.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UNO', 'name' => 'Unobtanium.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UNY', 'name' => 'Unity-Ingot.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UP', 'name' => 'UpToken.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'URO', 'name' => 'Uro.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'USDT', 'name' => 'Tether.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'UTK', 'name' => 'UTrust.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VEE', 'name' => 'BLOCKv.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VEN', 'name' => 'VeChain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VERI', 'name' => 'Veritaseum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VIA', 'name' => 'Viacoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VIB', 'name' => 'Viberate.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VIBE', 'name' => 'Vibe.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VIVO', 'name' => 'VIVO.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VOISE', 'name' => 'Voise.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VOX', 'name' => 'Voxels.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VPN', 'name' => 'VPNCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VRC', 'name' => 'Vericoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VRM', 'name' => 'Verium.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VRS', 'name' => 'Veros.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VSL', 'name' => 'vSlice.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VTC', 'name' => 'Vertcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'VTR', 'name' => 'vTorrent.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WABI', 'name' => 'WaBi.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WAN', 'name' => 'Wanchain.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WAVES', 'name' => 'Waves.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WAX', 'name' => 'Wax-Token.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WCT', 'name' => 'Waves-Community.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WDC', 'name' => 'WorldCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WGO', 'name' => 'WavesGo.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WGR', 'name' => 'Wagerr.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WINGS', 'name' => 'Wings.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WPR', 'name' => 'WePower.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WTC', 'name' => 'Walton.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'WTT', 'name' => 'Giga-Watt-Toke.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XAS', 'name' => 'Asch.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XAUR', 'name' => 'Xaurum.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XBC', 'name' => 'Bitcoin-Plu.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XBY', 'name' => 'XtraBYtes.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XCN', 'name' => 'Cryptonite.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XCP', 'name' => 'Counterparty.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XDN', 'name' => 'DigitalNote.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XEL', 'name' => 'Elastic.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XEM', 'name' => 'NEM.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XID', 'name' => 'Sphere-Identity.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XLM', 'name' => 'Stellar.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XMG', 'name' => 'Magi.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XMR', 'name' => 'Monero.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
              ['symbol' =>'XMT', 'name' => 'Metal.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XMY', 'name' => 'Myriadcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XPM', 'name' => 'Primecoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XRL', 'name' => 'Rialto.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XRP', 'name' => 'Ripple.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XSPEC', 'name' => 'Spectrecoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XST', 'name' => 'Stealthcoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XTZ', 'name' => 'Tezos.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XUC', 'name' => 'Exchange-Union.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XVC', 'name' => 'Vcash.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XVG', 'name' => 'Verge.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XWC', 'name' => 'WhiteCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XZC', 'name' => 'ZCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'XZR', 'name' => 'ZrCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'YEE', 'name' => 'Yee.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'YOYOW', 'name' => 'YOYOW.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZCC', 'name' => 'ZcCoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZCL', 'name' => 'Zclassic.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZCO', 'name' => 'Zebi.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZEC', 'name' => 'Zcash.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZEN', 'name' => 'ZenCash.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZET', 'name' => 'Zetacoin.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZIL', 'name' => 'Zilliqa.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZLA', 'name' => 'Zilla.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
            ['symbol' =>'ZRX', 'name' => '0x.', 'type' => 'digital', 'status' => 'on', 'created_at' => now()],
        ];

        foreach ($cryptos as $crypto) {
            DB::table('assets')->insert($crypto);
        }
    }
}
